### ISSUE TITLE
Bekreft tur fungerer ikke

### ISSUE THREAD

**Issue by hanspf** [eirikb/stfu#3]
Finner turen, men skjer ingenting når jeg trykker på den flotte grønne knappen. 
Sjekket og på stikkut.no og så at det ikke hadde blitt registrert noe tur

Brukte Safari på iOS. Har ikke testet andre nettlesere så vet ikke om det er generelt.

**Comment by eirikb** [comment]
Dette gjelder alle som ikke har "companions". Er på saken!
